### PR TITLE
Fix Sign Up/ Sign In

### LINKED ISSUE #112: Unable to Sign In after Pull Request
It looks like the sign in functionality is broken in the most recent build. The sign in functionality for google auth is also broken.

### PR DESCRIPTION
**Pull request by TheBrockstar**
- Fixed props being passed through app.js
 - Fixed redirect preventing signup from signin.

# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #112 

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

## Change status
- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?
- [x] Test A: Signed In/Up

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by Austinlp4 — APPROVED** [review]
Looks Good

File: client/src/components/SignUp/Types/SignUpTypes.js [hunk 1]
```diff
@@ -62,13 +63,13 @@ class SignUpTypes extends React.Component {
 
   componentDidMount = () => {
 
-    // If a user is signed in and on this page, re-direct th
+    // If a user is signed in and on this page, re-direct them to settings
     const user = firebase.auth().currentUser;
     if (user !== null) {
       if (this.props.currentSignedInUser) {
         this.props.history.push('/settings')
       } else {
```
Comment (Serrowxd) [inline client/src/components/SignUp/Types/SignUpTypes.js:71]: If I'm not mistaken, you should only need an `if` statement here so you can actually remove the `else` part of it.

I'm sure it's there for debugging, but in the future polishing updates we can just remove it.
